[32mINFO    [0m utils.recordlogs:conftest.py:61 //////////////////开始执行前置条件//////////////////
[32mINFO    [0m utils.recordlogs:precondition.py:64 执行前置条件:placeAnOrder
[32mINFO    [0m utils.recordlogs:readyaml.py:95 d:\MyCode\learn_Test\eCommerce_apitestV3\extract.yaml写入数据: 【{'orderNumber': '843696230618016930683'}】
[32mINFO    [0m utils.recordlogs:readyaml.py:95 d:\MyCode\learn_Test\eCommerce_apitestV3\extract.yaml写入数据: 【{'userId': '4985173412817324110'}】
[32mINFO    [0m utils.recordlogs:conftest.py:10 ********************用例开始********************
[32mINFO    [0m utils.recordlogs:apiclient.py:72 接口名称：校验商品订单状态接口
[32mINFO    [0m utils.recordlogs:apiclient.py:73 接口地址： http://127.0.0.1:8181//coupApply/cms/checkOrderStatus
[32mINFO    [0m utils.recordlogs:apiclient.py:74 接口方法：POST
[32mINFO    [0m utils.recordlogs:apiclient.py:75 请求头：{'Content-Type': 'application/json;charset=UTF-8'}
[32mINFO    [0m utils.recordlogs:apiclient.py:76 用例名称：无效校验-订单号不存在
[32mINFO    [0m utils.recordlogs:apiclient.py:85 请求参数：{'json': {'orderNumber': '2', 'timeStamp': 2}}
[32mINFO    [0m werkzeug:_internal.py:97 127.0.0.1 - - [13/Aug/2025 18:28:37] "POST /coupApply/cms/checkOrderStatus HTTP/1.1" 200 -
[32mINFO    [0m utils.recordlogs:assertions.py:39 ✅http状态码断言**通过**，预期状态码：【200】,实际状态码：【200】
[32mINFO    [0m utils.recordlogs:assertions.py:172 ✅不等断言**通过**，【error】预期值：【None】,实际值：【订单编号不存在】
[32mINFO    [0m utils.recordlogs:assertions.py:129 ✅相等断言**通过**，【error_code】预期值：【4000】,实际值：【4000】
[32mINFO    [0m utils.recordlogs:requestBase.py:112 用例【校验商品订单状态接口--无效校验-订单号不存在】执行成功✅✅✅✅✅✅✅✅✅✅
[32mINFO    [0m utils.recordlogs:conftest.py:12 ********************用例结束********************